- name: Postleaf playbook v0.0.2
  hosts: 127.0.0.1
  become: yes

  vars:
    current_user: ubuntu
    # !!! Don't add a trailing slash to the app_url !!!
    app_url: http://domain-or-ip-address
    app_port: 3000
    # You can generate a uuid with `echo $(uuidgen)`
    auth_secret: random_string 

  roles:
    - common
    - nodejs
    - nginx
    - postleaf
